### ISSUE TITLE
Is there any option to set one field do not be translated?

### ISSUE THREAD

**Issue by yzprofile** [lordnull/rec2json#13]
Example:

```
-record(r, {
    i = 0 :: integer(),
    n :: ignore()
}).
```

a = #a{i = 0, n = xxx}

after a:to_json(),
generate:

```
{"i" : 0}
```

**Comment by lordnull** [comment]
The default exported to_json/1 does all of the fields. However, because rec2json is careful when creating it's functions, you can implement your own to_json/1 to set the fields to add and alter.

```erlang
-module(r).
-record(r, {
    i = 0 :: integer(),
    n :: ignore()
}).
-export([to_json/1]).

to_json(Rec) ->
    ?MODULE:to_json([n], Rec).
```

**Comment by yzprofile** [comment]
Yep, That's one way to do that.

But is there any chance to do it in the library by using a type to indicate the field need to be declined ?.

**Comment by lordnull** [comment]
The are two technical reasons why it's not done.

There's no code path at the moment that would allow it to be easily implemented. Types are checked without access to the fully resulting json or the record itself, so adding it would be a lot of work.

The second is the types actually have meaning to erlang, specifically dialyzer. Now, doing a type along the lines of <code>r2j_type:ignored(pos_integer())</code> might work, but seems like even more effort to get that to make dialyzer happy.

In the projects I use rec2json for, I've started creating my own to_json/1 anyway because often I will not only need to hide fields, but also add new ones, such as a url if doing rest style returns.

So I can't say there's no chance, but expect it to take long enough you end up implementing your own to_json/1 in the meantime anyway :/

**Comment by yzprofile** [comment]
Thanks for explanation. That's very useful for a beginner as me 

Issue close. 

Thx. : )
