### ISSUE TITLE
It seems broken with atom

### ISSUE THREAD

**Issue by yzprofile** [lordnull/rec2json#14]
```erlang
-record(main, {
          test :: atom
         }).

Record = #main{
            test = lalala
           },
Json = Record:to_json(),

```

```bash

** exception error: bad argument: {test,lalala,{specific,[undefined,atom]}}
     in function  rec2json:'-to_json/2-fun-0-'/3 (src/rec2json.erl, line 126)
     in call from lists:foldl/3 (lists.erl, line 1261)
     in call from rec2json:to_json/2 (src/rec2json.erl, line 118)
     in call from main:test/0 (main.erl, line 20)

```

**Comment by yzprofile** [comment]
Fixed: https://github.com/lordnull/rec2json/pull/15/files

**Comment by lordnull** [comment]
This is intentional. Because one of the main use cases of rec2json is to take json from an external source and turn it into a record, it is a security risk to blindly turn strings into atoms. Atoms are never garbage collected, thus a malicious sender could fill up the atom table. Rec2json will only convert explicitly listed atoms in the type list, not any atom.

If you know the atoms you wish to use, you can redefine your record like so:
```erlang
-record(main, {
    test :: 'atom' | 'lalala' | 'another_atom'
}).
```
If you must have arbitrary atoms (which I strongly advise against), you can use a user-defined type:
```erlang
-module(main).
-record(main, {
    test :: main:atom_converter()
}).
-opaque atom_converter() :: atom().
-export_types([atom_converter/0]).
-export([atom_converter/0]).
atom_converter(Atom) when is_atom(Atom) ->
    {ok, atom_to_binary(Atom, utf8)};
atom_converter(Atom) when is_binary(Atom) ->
    {ok, binary_to_atom(Atom, ut8)};
atom_converter(_) ->
    error.
```

**Comment by yzprofile** [comment]
Thanks for your clear explanation.

Issue close.
