### ISSUE TITLE
issues generating json from list of nested records

### ISSUE THREAD

**Issue by sescobb27** [lordnull/rec2json#19]
Hi, i'm not sure if this is supported or not, but i'm having the following issue: 

i'm learning erlang passing a Node.js service to it, but i'm stock trying to map relationships between records and mapping them to json; i found your awesome library and it works perfectly until i tried to map to json a `has many` relationship.
I have some question is it supported and i'm doing something wrong? or it isn't? if it isn't can you point me what i need to make it work? or maybe is a bad idea to map those kind of relationships in erlang? as i said i'm just learning but there isn't anything said anywhere.
thanks in advance.

```erlang
-module (collection).
-compile([{parse_transform, rec2json}]).

-export ([new/5, add_product/2]).

-export_type([collection/0]).

-type status() :: active | inactive.

-record(collection, {
  id :: binary,
  title :: binary(),
  status :: status(),
  code  :: binary(),
  image  :: binary(),
  products :: [product:product()]
}).

-opaque collection() :: #collection{}.

-spec add_product(product:product(), collection()) -> collection().
add_product(Product, Collection) ->
  ProductList = Collection#collection.products,
  ProductSet = sets:from_list(ProductList),
  ProductSet2 = sets:add_element(Product, ProductSet),
  ProductList2 = sets:to_list(ProductSet2),
  Collection#collection{products = ProductList2}.
```

```erlang
-module (product).
-compile([{parse_transform, rec2json}]).

-export ([new/14]).

-export_type([product/0]).

-record (product,
{
  sku_base :: binary(),
  title :: binary(),
  description :: binary(),
  short_description :: binary(),
  fabric :: binary(),
  care :: binary(),
  col = collection:collection(),
  colors :: list(),
  sheerness :: pos_integer(),
  measurements :: list(),
  images :: list(),
  thumbnail :: binary(),
  price :: pos_integer(),
  sizes :: list()
}).

-opaque product() :: #product{}.
```

```
Col1 = collection:new(<<"Col1">>, active, <<"SM16">>, <<"url">>, []).
Prod = product:new(<<"">>, <<"">>, <<"">>, <<"">>, <<"">>, <<"">>, Col1, [], 7, [], [], <<"">>, 4000, ["00"]).
Col2 = collection:add_product(Prod, Col1).
product:to_json(Prod).
[{sku_base,<<>>},
 {title,<<>>},
 {description,<<>>},
 {short_description,<<>>},
 {fabric,<<>>},
 {care,<<>>},
 {col,{collection,undefined,<<"Col1">>,active,<<"SM16">>,
                  <<"url">>,undefined,[]}},
 {colors,[]},
 {sheerness,7},
 {measurements,[]},
 {images,[]},
 {thumbnail,<<>>},
 {price,4000},
 {sizes,["00"]}]

collection:to_json(Col2).
** exception error: bad argument: {products,[{product,<<>>,<<>>,<<>>,<<>>,<<>>,<<>>,
                                                      {collection,undefined,<<"Col1">>,active,<<"SM16">>,
                                                                  <<"url">>,undefined,[]},
                                                      [],7,[],[],<<>>,4000,
                                                      ["00"]}],
                                            {specific,[undefined,
                                                       {list,{specific,[{product,product,[]}]}}]}}
     in function  rec2json:'-to_json/2-fun-1-'/3 (/home/kiro/Documents/Erlang/ec_api/_build/default/lib/rec2json/src/rec2json.erl, line 145)
     in call from lists:foldl/3 (lists.erl, line 1262)
     in call from rec2json:to_json/2 (/home/kiro/Documents/Erlang/ec_api/_build/default/lib/rec2json/src/rec2json.erl, line 135)
```

**Comment by lordnull** [comment]
It is supported, but there needs to be a bit extra work to get it to work seamlessly.

When rec2json encounters a user defined type, it checks if there's a module that exports a function with an arty 1 greater than the user defined type.

In your example, the collection has a type of type like `product:product()`. `rec2json` will check if there's a module `product` which exports `product/1`, passing in the tuple when converting to json, or the json when converting from.

You should be able to change your product module like so:

```erlang
%% your existing code up to the export line
-export([new/14]).
-export([product/1]).

%% existing code
%% ...
%% additions

%% note the returns. If the from_json had no warnings, it return {ok, Record}. We have to wrap
%% the to_json/1 call in an ok tuple to indicate that it was able to encode the value properly.
product(Record) when is_record(Record, product) ->
	{ok, to_json(Record)};
product(Json) ->
	from_json(Json).
```

**Comment by sescobb27** [comment]
Hi thanks for your response, now it shows a different error message
![image](https://cloud.githubusercontent.com/assets/1157892/14593372/361b7418-04ef-11e6-900a-fc023ef844af.png)

**Comment by lordnull** [comment]
The short answer is you've mistyped the spec for your collections field, and this means rec2json is choking on what is bad data based on the type. Change the collection record's products field type to `[binary()]`, and this will make the crash go away.

This was funky to figure out. So, when you defined your collection record you gave the products field a type of `product:product()`. In the product module, you defined the type `product/0` as `#product{}`. To help rec2json along, we've added a function to the product module called product that translates `#product{}` to the json representation. The function I created for you only checks if the argument passed in is a `#product{}`, otherwise it assumes it's json. In the case of `#product{}`, it calls `to_json/1`, otherwise it calls `from_json/1`.

So, rec2json transforms each field of the collection, and gets to the products field. It passes `[<<"ProdId">>]` to our transformation function. It doesn't match against the first clause, but it does against the second. We end up calling `from_json/1`, which expects a prop list. It gets `[binary()]`, and ends up exploding because the head of the list is not `{key(), value()}`.

The "most correct" solution is in the short answer: change the type of the field to how it is actually being used. If you instead want to use it either way, you'll need to tighten up the `product:product/1` a bit.
